name = "iplcforms"
compatibility_date = "2024-12-31"
pages_build_output_dir = ".vercel/output/static"

# Edge runtime compatibility - removed nodejs_compat for @cloudflare/next-on-pages
# compatibility_flags = ["nodejs_compat"]

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "iplcforms"
database_id = "a484d14e-fa44-48b1-a590-bd0b29aa3593"

[vars]
# Environment variables (configure actual values in Cloudflare dashboard)
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY_HERE"
ADMIN_COOKIE_SECRET = "YOUR_ADMIN_COOKIE_SECRET_HERE"