name = "iplcforms"
compatibility_date = "2024-12-31"
pages_build_output_dir = ".vercel/output/static"

# Edge runtime compatibility - removed nodejs_compat for @cloudflare/next-on-pages
# compatibility_flags = ["nodejs_compat"]

# D1 Database binding (configure database_id in Cloudflare dashboard)
[[d1_databases]]
binding = "DB"
database_name = "iplc-forms-db"
database_id = "YOUR_D1_DATABASE_ID_HERE"

[vars]
# Environment variables (configure actual values in Cloudflare dashboard)
OPENAI_API_KEY = "YOUR_OPENAI_API_KEY_HERE"
ADMIN_COOKIE_SECRET = "YOUR_ADMIN_COOKIE_SECRET_HERE"