name = "iplcforms"
compatibility_date = "2024-12-31"
pages_build_output_dir = ".vercel/output/static"

# Edge runtime compatibility - removed nodejs_compat for @cloudflare/next-on-pages
# compatibility_flags = ["nodejs_compat"]

[vars]
# Removed Node.js specific variables for edge runtime compatibility
# NODE_VERSION = "20"
# NODE_ENV     = "production"