name = "iplcforms"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# OpenNext Cloudflare configuration
main = ".open-next/worker.js"

[assets]
binding = "ASSETS"
directory = ".open-next/assets"

[[d1_databases]]
binding = "DB"
database_name = "iplcforms"
database_id = "a484d14e-fa44-48b1-a590-bd0b29aa3593"

[vars]
ENVIRONMENT = "production"