name = "iplcforms"
compatibility_date = "2025-07-02"
pages_build_output_dir = ".vercel/output/static"   # <- REQUIRED for Pages

# Enable Node polyfills that OpenNext expects
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_VERSION = "20"
NODE_ENV     = "production"